### ISSUE TITLE
Exception has occurred. Segmentation fault

### ISSUE THREAD

**Issue by comewei** [aiyolo/leetcode-debug#1]
啥都没有运行，为什么会段错误
![image](https://user-images.githubusercontent.com/49831107/197337755-1ffbd01d-1fdc-47e8-aedd-ad7e33ecafae.png)

**Comment by aiyolo** [comment]
建议检查一下读取输入文件的位置对不对，如果不对的话，读到的空数据自然和函数变量匹配不了
